---

all:
  hosts:
    new_host:
      ansible_host: 192.168.56.107
   #   ansible_port: 
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_password: ubuntu  
   #   ansible_ssh_private_key_file: ~/.ssh/

