---

all:
  hosts:
    Zabbix_agent:
      ansible_host:
      ansible_port: 
      ansible_connection: ssh
      ansible_user: ubuntu
   #   ansible_password:  
      ansible_ssh_private_key_file: ~/.ssh/

