---

#    - name: Create a ext4 filesystem on /dev/vdb
#      become: yes
#      community.general.filesystem:
#        fstype: ext4
#        dev: /dev/vdb
 
#    - name: Add a note
#      become: yes
#      command: sh -c "echo '/dev/vdb /mnt/storage ext4 defaults 0 0' >> /etc/fstab" 
      
#    - name: Mount
#      become: yes
#      command: sh -c "mount -a"
#      args:
#        warn: no
- name: create directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /mnt/storage
    - /mnt/storage/services
    - /mnt/storage/logs
    - /mnt/storage/docker
    - /mnt/storage/db
  tags:
    - create.dirs    
    
- name: Create group
  become: yes
  group:
    name: deployer
    state: present
  tags:
    - create.group

- name: Create deployer user
  become: yes
  user:
    name: deployer
    password: $1$yIwXTwLC$wRAV/wBPA27eqmL2FI4EZ/
    groups: docker,sudo,deployer
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/deployer
  tags: 
    -create.user

- name: Changing privelegy
  command:  sh -c "sudo chown -R deployer:deployer /mnt/storage"
  become: yes
  tags:
    - change.privelegy

- name: Create symlinks
  become: yes
  file:
    src: "/mnt/storage/{{ item.src }}"
    dest: "/home/deployer/{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: 'services', dest: 'services' }
    - { src: 'logs', dest: 'logs' }
    - { src: 'db', dest: 'db' }
    - { src: 'docker', dest: 'docker' }
  tags:
    - create.symlink
           


