---
 
- name: Update apt cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - update.cache

- name: Install dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ca-certificates
    - curl
    - gnupg-agent
    - lsb-release
  tags:
    - dependencies

- name: Add an apt signing key for Docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: 
    - add.key

- name: Add dep package
  become: yes
  command: sh -c 'echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  tags: 
    - add.repo

- name: Install docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags:
    - install.docker

- name: Add ubuntu to docker group
  become: yes
  user:
    name: "ubuntu"
    group: docker
  tags:
    - ubuntu.to.docker

- name: Add deployer to docker group
  become: yes
  user:
    name: "deployer"
    group: docker
  tags:
    deployer.to.docker

- name: uname -s
  command: uname -s
  register: result_uname_s
  tags:
    - uname

- set_fact:
    uname_s: "{{ result_uname_s.stdout }}"
  tags:
    - uname

- name: uname -m
  command: uname -m
  register: result_uname_m
  tags:
    - uname

- set_fact:
    uname_m: "{{ result_uname_m.stdout }}"
  tags: 
    - uname

- name: Download docker-compose {{ docker_compose_version }}
  become: yes
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{uname_s}}-{{uname_m}}
    dest: /usr/local/bin/docker-compose
    mode: '+x'
  tags:
    - download.docker.compose 

- name: Add symlink
  become: yes
  file:
    src: "/usr/local/bin/docker-compose"
    dest: "/usr/bin/docker-compose"
    state: link
    force: yes
  tags:
    - add.symlink

 


