---

- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{nvm_version}}/install.sh | bash
    warn: false
  args:
    executable: /bin/bash
    creates: "$HOME/.nvm/nvm.sh"
